version: '3'

services:
  database:
    restart: always
    image: "postgres:16.2"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ilya58
      POSTGRES_DB: postgres
      PORT: 5432
    ports:
      - "5432:5432"


  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

