server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: SMSMassage
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
    drop-first: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ilya58
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
clients:
  url: http://localhost:8080


