server:
  port: 8081
spring:
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/Clients
    username: postgres
    password: ilya58
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
clients:
  url: localhost:8080

config:
  topic: messageSMS
